// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjmc__9Y8jgwHHH88SehNMG4RbqYAeNrI',
    appId: '1:42650859219:android:8e5bc42a8f559769178626',
    messagingSenderId: '42650859219',
    projectId: 'uni-stash',
    storageBucket: 'uni-stash.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI1ziVbPfSMdvyDEP7kPQ4sBrovRmUoNs',
    appId: '1:42650859219:android:8e5bc42a8f559769178626',
    messagingSenderId: '42650859219',
    projectId: 'uni-stash',
    storageBucket: 'uni-stash.firebasestorage.app',
    androidClientId: '42650859219-c2im3bhdvoheu5n9duqqbeo56m80hraq.apps.googleusercontent.com',
    iosClientId: '42650859219-6lu7i11f3leo7rv954v53pn0lj8u78a0.apps.googleusercontent.com',
    iosBundleId: 'com.gettoknowdavid.unistash',
  );
}
