$kind: environment
name: Dev (Local)
values:
  - key: baseUrl
    value: http://localhost:8080
    type: default
  - key: accessToken
    value: ""
    type: secret
  - key: refreshToken
    value: ""
    type: secret
  - key: adminAccessToken
    value: ""
    type: secret
  - key: adminRefreshToken
    value: ""
    type: secret
  - key: adminId
    value: ""
    type: secret
