import 'package:forui/forui.dart';

//
// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FTheme.neutral.light.touch.color,
///  style: FTheme.neutral.light.touch.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FTheme.neutral.light.touch.color,
///    style: FTheme.neutral.light.touch.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/guides/customizing-themes for more information.
FFormFieldStyle formFieldStyle({
  required FColors colors,
  required FTypography typography,
  required bool touch,
}) {
  final textStyle = touch ? typography.display.xs : typography.display.sm;
  return FFormFieldStyle(
    labelTextStyle: FVariants.from(
      textStyle.copyWith(
        color: colors.foreground,
        fontWeight: .w800,
        letterSpacing: 0.42,
      ),
      variants: {
        [.error]: .delta(color: colors.error),
        [.disabled]: .delta(color: colors.disable(colors.foreground)),
        [.disabled.and(.error)]: .delta(color: colors.disable(colors.error)),
      },
    ),
    descriptionTextStyle: FVariants.from(
      textStyle.copyWith(color: colors.mutedForeground),
      variants: {
        [.disabled]: .delta(color: colors.disable(colors.mutedForeground)),
      },
    ),
    errorTextStyle: FVariants.from(
      textStyle.copyWith(color: colors.error),
      variants: {
        [.disabled]: .delta(color: colors.disable(colors.error)),
      },
    ),
  );
}
