//
// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

import 'package:forui/forui.dart';
import 'package:material_ui/material_ui.dart';

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FTheme.neutral.light.touch.color,
///  style: FTheme.neutral.light.touch.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FTheme.neutral.light.touch.color,
///    style: FTheme.neutral.light.touch.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/guides/customizing-themes for more information.
FTextFieldStyle usTextFieldStyle({
  required FColors colors,
  required FStyle style,
  required FTypography typography,
  required FVariants<
    FTextFieldVariantConstraint,
    FTextFieldVariant,
    IconThemeData,
    IconThemeDataDelta
  >
  iconStyle,
  required FButtonStyle buttonStyle,
  required BoxConstraints constraints,
  required EdgeInsetsGeometry contentPadding,
}) {
  final textStyle = typography.body.sm;
  final labelStyle = FLabelStyles.inherit(style: style).verticalStyle;
  return FTextFieldStyle(
    keyboardAppearance: colors.brightness,
    color: FVariants(
      colors.card,
      variants: {
        [.disabled]: colors.disable(colors.card),
      },
    ),
    cursorColor: colors.primary,
    constraints: constraints,
    contentPadding: contentPadding,
    iconStyle: iconStyle,
    clearButtonStyle: buttonStyle,
    obscureButtonStyle: buttonStyle.copyWith(
      tappableStyle: const .delta(
        motion: .delta(bounceTween: FTappableMotion.noBounceTween),
      ),
    ),
    contentTextStyle: FVariants.from(
      textStyle.copyWith(color: colors.foreground),
      variants: {
        [.disabled]: .delta(color: colors.disable(colors.foreground)),
      },
    ),
    hintTextStyle: FVariants.from(
      textStyle.copyWith(color: colors.mutedForeground),
      variants: {
        [.disabled]: .delta(color: colors.disable(colors.mutedForeground)),
      },
    ),
    counterTextStyle: FVariants.from(
      textStyle.copyWith(color: colors.foreground),
      variants: {
        [.disabled]: .delta(color: colors.disable(colors.foreground)),
      },
    ),
    border: FVariants(
      OutlineInputBorder(
        borderSide: BorderSide(color: colors.border, width: style.borderWidth),
        borderRadius: style.borderRadius.md,
      ),
      variants: {
        [.focused]: OutlineInputBorder(
          borderSide: BorderSide(color: colors.primary, width: 3),
          borderRadius: style.borderRadius.md
        ),
        [.disabled]: OutlineInputBorder(
          borderSide: BorderSide(
            color: colors.disable(colors.border),
            width: style.borderWidth,
          ),
          borderRadius: style.borderRadius.md,
        ),
        [.error]: OutlineInputBorder(
          borderSide: BorderSide(color: colors.error, width: style.borderWidth),
          borderRadius: style.borderRadius.md,
        ),
        [.error.and(.disabled)]: OutlineInputBorder(
          borderSide: BorderSide(
            color: colors.disable(colors.error),
            width: style.borderWidth,
          ),
          borderRadius: style.borderRadius.md,
        ),
      },
    ),
    labelTextStyle: style.formFieldStyle.labelTextStyle,
    descriptionTextStyle: style.formFieldStyle.descriptionTextStyle,
    errorTextStyle: style.formFieldStyle.errorTextStyle,
    labelPadding: labelStyle.labelPadding,
    descriptionPadding: labelStyle.descriptionPadding,
    errorPadding: labelStyle.errorPadding,
    childPadding: labelStyle.childPadding,
    cursorWidth: 2,
    clearButtonPadding: const .directional(end: 4),
    obscureButtonPadding: const .directional(end: 4),
    scrollPadding: const .all(20),
    labelMotion: const FLabelMotion(),
  );
}
