[package]
name = "uni-stash-be"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-governor = "0.10.0"
actix-web = "4.14.1"
anyhow = "1.0.104"
argon2 = { version = "0.5.3", features = ["default"] }
aws-sdk-s3 = { version = "1.141.0", features = ["rustls"] }
dotenvy = "0.15.7"
hex = "0.4.3"
jsonwebtoken = { version = "11.0.0", features = ["rust_crypto"] }
rand = "0.10.2"
reqwest = { version = "0.13.4", features = ["json", "rustls"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha2 = "0.11.0"
sqlx = { version = "0.9.0", features = ["macros", "migrate", "postgres", "runtime-tokio", "time", "tls-rustls", "uuid"] }
thiserror = "2.0.20"
time = { version = "0.3.55", features = ["serde", "serde-well-known"] }
tokio = "1.53.1"
tracing = "0.1.44"
tracing-actix-web = "0.7.22"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
uuid = { version = "1.24.1", features = ["serde", "v4"] }
validator = { version = "0.21.0", features = ["derive"] }

[dev-dependencies]
actix-rt = "2.10"
wiremock = "0.6"
