name: Deploy to Render

on:
  push:
    branches:
      - master # Triggers when you push to master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST "https://api.render.com/deploy/srv-da170p8u01pc739k5t80?key=2TdlMk3G77M"
